export enum ErrorTypeToClient {
    USER_EXISTS,
    USER_DOESNT_EXIST,
    USER_ISNT_RECEIVING_INVITE,
    USER_MISSING_PERMISSION,
    USER_NOT_IN_CHAT,
    USER_NO_REQUEST,

    USER_BLOCKED,
    USER_BLOCKED_U,
    USER_FRIENDED_U,

    CANNOT_FRIEND_REQUEST_SELF,
    ALREADY_CONNECTED,

    INVITE_DOESNT_EXIST,

    SESSION_INVALID,

    CHALLENGE_EXPIRED,
    CHALLENGE_FAILED,

    INTERNAL_ERROR,

    ACCOUNT_DELETED,
    MISSING_SESSION_ID,

    CHAT_DOESNT_EXIST,
    CHAT_NOT_PARTICIPANT,
    CHAT_IS_DM,
    CHAT_IS_GROUP,

    DM_EXISTS,

    MESSAGE_DOESNT_EXIST,
    
    TYPE_NOT_IMPLEMENTED,
}

export enum ErrorTypeToServer {

}