export enum ErrorTypeToClient {
    USER_EXISTS,
    USER_DOESNT_EXIST,
    USER_ISNT_RECEIVING_INVITE,
    USER_MISSING_PERMISSION,

    INVITE_DOESNT_EXIST,

    SESSION_INVALID,

    CHALLENGE_EXPIRED,
    CHALLENGE_FAILED,

    INTERNAL_ERROR,

    ACCOUNT_DELETED,
    MISSING_SESSION_ID,

    CHAT_DOESNT_EXIST,
    CHAT_NOT_PARTICIPANT,
    CHAT_IS_DM,
    CHAT_IS_GROUP,

    MESSAGE_DOESNT_EXIST,
}

export enum ErrorTypeToServer {

}