export enum MessageTypeToClient {
    ERROR,
    SUCCESS,

    CHALLENGE_ISSUED,

    CHAT_CREATED,
    CHAT_DELETED,
    
    GROUP_CHAT_EDITED,

    PARTICIPANT_INVITED,
    PARTICIPANT_UNINVITED,
    PARTICIPANT_INVITE_ACCEPTED,
    PARTICIPANT_INVITE_DECLINED,
    
    MESSAGE_CREATED,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
}

export enum MessageTypeToServer {
    NONE,

    CHALLENGE_REQUEST,
    CHALLENGE_VERIFY_AND_EXECUTE,
    
    ACCOUNT_CREATE,
    ACCOUNT_SET_SETTING,
    ACCOUNT_GET_SETTINGS,
    ACCOUNT_GET_CHATS,
    ACCOUNT_GET_INVITES,
    USER_GET_INFO,

    DM_CREATE,

    GROUP_CHAT_CREATE,
    GROUP_CHAT_EDIT,

    CHAT_GET,
    CHAT_GET_PARTICIPANTS_KEYS,
    CHAT_DELETE,
    CHAT_GET_MESSAGES,

    PARTICIPANT_INVITE,
    PARTICIPANT_UNINVITE,

    INVITE_ACCEPT,
    INVITE_GET,
    INVITE_DECLINE,

    MESSAGE_CREATE,
    MESSAGE_EDIT,
    MESSAGE_DELETE,
    MESSAGE_GET,
}