export enum MessageTypeToClient {
    ERROR,
    SUCCESS,
    TYPE_NOT_IMPLEMENTED,

    CHALLENGE_ISSUED,

    GROUP_CHAT_DELETED,
    GROUP_CHAT_EDITED,

    DM_CHAT_DELETED,

    PARTICIPANT_INVITED,
    PARTICIPANT_INVITE_ACCEPTED,
    PARTICIPANT_REMOVED,
    
    MESSAGE_CREATED,
    MESSAGE_EDITED,
    MESSAGE_DELETED,
}

export enum MessageTypeToServer {
    NONE,

    CHALLENGE_REQUEST,
    CHALLENGE_VERIFY_AND_EXECUTE,
    
    ACCOUNT_CREATE,
    ACCOUNT_GET_SETTINGS,
    ACCOUNT_GET_CHATS,
    USER_GET_INFO,

    GROUP_CHAT_CREATE,
    GROUP_CHAT_EDIT,
    GROUP_CHAT_GET,
    GROUP_CHAT_GET_PARTICIPANTS_KEYS,
    GROUP_CHAT_DELETE,

    PARTICIPANT_INVITE,
    PARTICIPANT_REMOVE,

    DM_CHAT_GET,
    DM_CHAT_GET_PARTICIPANTS_KEYS,
    DM_CHAT_DELETE,

    INVITE_ACCEPT,

    MESSAGE_CREATE,
    MESSAGE_EDIT,
    MESSAGE_DELETE,
}